name: Run Local JUnit 5 Test

on:
  workflow_dispatch:

jobs:
  run-maven-test:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Maven Test with Proxy
        shell: cmd
        run: |
          mvn -Dhttp.proxyHost=cp-isa-isa.bsb.ge -Dhttp.proxyPort=8080 -Dhttps.proxyHost=cp-isa-isa.bsb.ge -Dhttps.proxyPort=8080 -Dtest=SuitTest test
        working-directory: D:\projects\NewAppTesting
