name: Run Local JUnit 5 Test

on:
  workflow_dispatch:

jobs:
  run-maven-test:
    runs-on: self-hosted # იყენებს შენს SOFT-26-207 რანერს

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Maven Test
        run: mvn -Dtest=SuitTest test
        working-directory: D:\projects\NewAppTesting
