name: Run Local JUnit 5 Test

on:
  workflow_dispatch:

jobs:
  run-maven-test:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Maven Test
        shell: cmd
        run: |
          start /wait "Maven Tests" cmd /c "cd /d C:\Projects\IdeaProjects\NewAppTesting && mvn test -Dtest=SuitTest"
